const router = require('express').Router();
const { authenticate } = require('../middleware/auth');
const authCtrl = require('../controllers/auth.controller');
const chatCtrl = require('../controllers/chat.controller');
const userCtrl = require('../controllers/user.controller');
const mediaCtrl = require('../controllers/media.controller');
router.post('/auth/send-otp', authCtrl.sendOTP);
router.post('/auth/verify-otp', authCtrl.verifyOTP);
router.post('/auth/refresh', authCtrl.refreshToken);
router.put('/auth/register-key', authenticate, authCtrl.registerPublicKey);
router.get('/users/me', authenticate, userCtrl.getMe);
router.put('/users/me', authenticate, userCtrl.updateProfile);
router.get('/users/search', authenticate, userCtrl.searchUsers);
router.get('/users/:userId', authenticate, userCtrl.getUserProfile);
router.post('/users/:userId/block', authenticate, userCtrl.blockUser);
router.get('/chats', authenticate, chatCtrl.getChats);
router.post('/chats/direct', authenticate, chatCtrl.createDirectChat);
router.post('/chats/group', authenticate, chatCtrl.createGroupChat);
router.get('/chats/:chatId/messages', authenticate, chatCtrl.getMessages);
router.post('/chats/:chatId/members', authenticate, chatCtrl.addGroupMembers);
router.delete('/chats/:chatId/leave', authenticate, chatCtrl.leaveGroup);
router.post('/media/upload', authenticate, mediaCtrl.uploadMedia);
module.exports = router;
